-- Supabase SQL migration for ticket purchases
CREATE TABLE IF NOT EXISTS tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  ticket_type text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  amount integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  reference text,
  paystack_response jsonb,
  requested_at timestamptz NOT NULL DEFAULT now(),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
